name: Indomitable
base-image: ghcr.io/ublue-os/base-main
fedora-version: 38
description: An attempt at a working Hyprland uBlue Image.

scripts:
  pre:
    - autorun.sh
  post:
    - autorun.sh
rpm:
  repos:
    - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-38/solopasha-hyprland-fedora-38.repo
    - https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-38/erikreider-SwayNotificationCenter-fedora-38.repo
    - https://copr.fedorainfracloud.org/coprs/eddsalkield/swaylock-effects/repo/fedora-38/eddsalkield-swaylock-effects-fedora-38.repo
    - https://copr.fedorainfracloud.org/coprs/dngray/sddm-sugar-dark/repo/fedora-38/dngray-sddm-sugar-dark-fedora-38.repo
    
  install:
    # Needed for yafti (the first boot installer). Remove if you're not using yafti.
    - python3-pip
    - libadwaita

    # System Tools
    - blueman
    - bolt
    - fprintd-pam
    - gnome-keyring-pam
    - lxqt-policykit
    - pavucontrol
    - brightnessctl
    - pinentry-gnome3
    - plymouth-system-theme
    - polkit
    - system-config-printer
    - wev
    - wl-clipboard
    - xorg-x11-server-Xwayland-23.1.2-1.fc38.x86_64
    - kanshi
    - playerctl
    - pulseaudio-utils
    - clipman
    - tumbler
    - btop
    - imv
    - mpd
    - mpv
    - wtype
    - wlr-randr
    - gamescope
    - wireplumber
    - pipewire-gstreamer
    - pipewire-pulseaudio
    - pipewire-alsa
    - pipewire-jack-audio-connection-kit
    - pipewire-plugin-libcamera
    - stow
    - pam-u2f
    - pamu2fcfg
    - fido2-tools
    - unrar
    - tar
    - p7zip
    - xdg-user-dirs

    ## Network manager and vpn
    - network-manager-applet
    - NetworkManager-l2tp-gnome
    - NetworkManager-libreswan-gnome
    - NetworkManager-openconnect-gnome
    - NetworkManager-openvpn-gnome
    - NetworkManager-pptp-gnome
    - NetworkManager-sstp-gnome
    - NetworkManager-vpnc-gnome

    # Virtualization 
    - qemu
    - virt-install
    - virt-manager
    - virt-viewer
    - libvirt-client
    - libvirt-daemon-kvm

    # Theming
    - qt5ct
    - qt6ct
    - lxappearance
    - qt5-qtwayland
    - qt6-qtwayland
    - kvantum
    - gtk-murrine-engine

    # Terminal
    - kitty

    # GUI
    - sddm
    - sddm-sugar-dark
    - swayidle
    - swaylock-effects
    - SwayNotificationCenter
    - wlogout
    - wlsunset
    - xdg-desktop-portal-hyprland
    - xdg-desktop-portal-gtk
    - waybar-hyprland
    - hyprpicker
    - hyprpaper
    - hyprland-plugins
    - hyprland-autoname-workspaces
    - hyprland
    - hyprland-contrib
    - hyprshot

    # File Manager
    - Thunar
    - thunar-archive-plugin

  remove:
    - firefox
    - firefox-langpacks
    - htop

firstboot:
  yafti: false
  flatpaks:
  - org.mozilla.firefox
