name: Indomitable
base-image: ghcr.io/ublue-os/base-main
fedora-version: 38
description: An attempt at a working Hyprland uBlue Image.

scripts:
  pre:
    - autorun.sh
  post:
    - autorun.sh

rpm:
  repos:
    - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-38/solopasha-hyprland-fedora-38.repo
    - https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-38/erikreider-SwayNotificationCenter-fedora-38.repo
    - https://copr.fedorainfracloud.org/coprs/trs-sod/swaylock-effects/repo/fedora-38/trs-sod-swaylock-effects-fedora-38.repo
    - https://copr.fedorainfracloud.org/coprs/dngray/sddm-sugar-dark/repo/fedora-38/dngray-sddm-sugar-dark-fedora-38.repo
    
  install:
    # Needed for yafti (the first boot installer). Remove if you're not using yafti.
    - python3-pip
    - libadwaita

    # System Tools
    - blueman
    - udiskie
    - fprintd-pam
#    - gnome-keyring-pam
    - lxqt-policykit
    - pavucontrol
    - brightnessctl
    - pinentry-gnome3
    - polkit
    - system-config-printer
    - wev
    - wl-clipboard
#    - xorg-x11-server-Xwayland
    - kanshi
    - playerctl
    - pulseaudio-utils
    - clipman
    - btop
    - imv
    - wtype
    - wlr-randr
    - gamescope
    - wireplumber
    - pipewire-gstreamer
    - pipewire-pulseaudio
    - pipewire-alsa
    - pipewire-jack-audio-connection-kit
    - pipewire-plugin-libcamera

    ## Network manager and vpn
    - network-manager-applet
    - NetworkManager-l2tp-gnome
    - NetworkManager-openvpn-gnome
    - NetworkManager-pptp-gnome
    - NetworkManager-sstp-gnome
    - NetworkManager-bluetooth
    - NetworkManager-wifi

    # Theming
    - qt5ct
    - qt6ct
    - lxappearance
    - qt5-qtwayland
    - qt6-qtwayland
    - kvantum
    - gtk-murrine-engine

    # Terminal
    - kitty

    # GUI
    - rofi
    - swayidle
    - swaylock-effects
    - SwayNotificationCenter
    - wlogout
    - wlsunset
    - xdg-desktop-portal-hyprland
    - xdg-desktop-portal-gtk
    - waybar-hyprland
    - hyprpicker
    - hyprpaper
    - hyprland-plugins
    - hyprland-autoname-workspaces
    - hyprland
    - hyprland-contrib
    - hyprshot
    - slurp

    # Extras
    - mpd
    - cava

    # sddm stuff
    - sddm-wayland-generic
    - sddm-sugar-dark

    # File Manager
    - Thunar
    - thunar-archive-plugin
    - unrar

  remove:
    - firefox
    - firefox-langpacks
    - htop

firstboot:
  yafti: true
  flatpaks:
  - org.mozilla.firefox
