# image will be published to ghcr.io/<user>/<name>
name: Indomitable
# description will be included in the image's metadata
description: An attempt at a working Hyprland uBlue Image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 38 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    remove:
    - xorg-x11-server-Xwayland
    - firefox # default firefox removed in favor of flatpak
    - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
    - htop

  - type: rpm-ostree
    repos:
    - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-38/solopasha-hyprland-fedora-38.repo
    #- https://copr.fedorainfracloud.org/coprs/sentry/xone/repo/fedora-38/sentry-xone-fedora-38.repo
    #- https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-38/erikreider-SwayNotificationCenter-fedora-38.repo
    - https://copr.fedorainfracloud.org/coprs/trs-sod/swaylock-effects/repo/fedora-38/trs-sod-swaylock-effects-fedora-38.repo
    - https://copr.fedorainfracloud.org/coprs/dngray/sddm-sugar-dark/repo/fedora-38/dngray-sddm-sugar-dark-fedora-38.repo
    install:
    # Needed for yafti (the first boot installer). Remove if you're not using yafti.
    - python3-pip
    - libadwaita

    # System Tools
    - blueman
    - udiskie
    - fprintd-pam
    - gnome-keyring-pam
    - polkit-gnome
    - pavucontrol
    - brightnessctl
    - pinentry-gnome3
    - polkit
    - system-config-printer
    - wev
    - wl-clipboard
    - xorg-x11-server-Xwayland
    - kanshi
    - playerctl
    - pulseaudio-utils
    - clipman
    - btop
    - imv
    - wtype
    - wlr-randr
    - gamescope
    - wireguard-tools
    - wireplumber
    - pipewire-gstreamer
    - pipewire-pulseaudio
    - pipewire-alsa
    - pipewire-jack-audio-connection-kit
    - pipewire-plugin-libcamera
    - xdg-user-dirs

    ## Network manager and vpn
    - network-manager-applet
    - NetworkManager-l2tp-gnome
    - NetworkManager-openvpn-gnome
    - NetworkManager-pptp-gnome
    - NetworkManager-sstp-gnome
    - NetworkManager-bluetooth
    - NetworkManager-wifi

    # Theming
    - qt5ct
    - qt6ct
    - lxappearance
    - qt5-qtwayland
    - qt6-qtwayland
    - kvantum
    - gtk-murrine-engine

    # Terminal
    - kitty

    # GUI
    - rofi
    - swayidle
    - swaylock-effects
    - SwayNotificationCenter
    - wlogout
    - wlsunset
    - xdg-desktop-portal-hyprland
    - xdg-desktop-portal-gtk
    - waybar-git
    - hyprpicker
    - hyprpaper
    - hyprland-plugins
    - hyprland-autoname-workspaces
    - hyprland
    - hyprland-contrib
    - hyprshot
    - slurp

    # Extras
#    - mpd
    - cava

    # sddm stuff
    - sddm-wayland-generic
    - sddm-sugar-dark

    # File Manager
    - Thunar
    - thunar-archive-plugin
    - unrar
    # Install after removing
    - xorg-x11-server-Xwayland

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - fonts # selection of common good free fonts
      - justfiles # add "!include /usr/share/ublue-os/just/bling.just"
                  # in your custom.just (added by default) or local justfile
      #- nix-installer # shell shortcuts for determinate system's nix installers
      #- ublue-os-wallpapers
      #- ublue-update # https://github.com/ublue-os/ublue-update
      - dconf-update-service # a service unit that updates the dconf db on boot
      - devpod # https://devpod.sh/ as an rpm


  - type: yafti # if included, yafti and it's dependencies (pip & libadwaita)
                #  will be installed and set up
    custom-flatpaks: # this section is optional
      # - Celluloid: io.github.celluloid_player.Celluloid
      - Firefox: org.mozilla.firefox

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
